/*
 * generated by Xtext 2.14.0
 */
package com.zazuko.experimental.rmdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RdfMappingAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/zazuko/experimental/rmdsl/parser/antlr/internal/InternalRdfMapping.tokens");
	}
}
