/**
 * generated by Xtext 2.14.0
 */
package com.zazuko.experimental.rmdsl.web;

import com.zazuko.experimental.rmdsl.web.AbstractRdfMappingWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class RdfMappingWebModule extends AbstractRdfMappingWebModule {
}
