/**
 * generated by Xtext 2.14.0
 */
package com.zazuko.experimental.rmdsl.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.zazuko.experimental.rmdsl.RdfMappingRuntimeModule;
import com.zazuko.experimental.rmdsl.RdfMappingStandaloneSetup;
import com.zazuko.experimental.rmdsl.ide.RdfMappingIdeModule;
import com.zazuko.experimental.rmdsl.web.RdfMappingWebModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class RdfMappingWebSetup extends RdfMappingStandaloneSetup {
  @Override
  public Injector createInjector() {
    RdfMappingRuntimeModule _rdfMappingRuntimeModule = new RdfMappingRuntimeModule();
    RdfMappingIdeModule _rdfMappingIdeModule = new RdfMappingIdeModule();
    RdfMappingWebModule _rdfMappingWebModule = new RdfMappingWebModule();
    return Guice.createInjector(Modules2.mixin(_rdfMappingRuntimeModule, _rdfMappingIdeModule, _rdfMappingWebModule));
  }
}
