/*
 * generated by Xtext 2.14.0
 */
package com.zazuko.experimental.rmdsl.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link RdfMappingWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractRdfMappingWebModule extends DefaultWebModule {

}
