/**
 * generated by Xtext 2.14.0
 */
package com.zazuko.experimental.rmdsl.ui.contentassist;

import com.zazuko.experimental.rmdsl.ui.contentassist.AbstractRdfMappingProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RdfMappingProposalProvider extends AbstractRdfMappingProposalProvider {
}
