/*
 * generated by Xtext 2.14.0
 */
package com.zazuko.experimental.rmdsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractRdfMappingValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(com.zazuko.experimental.rmdsl.rdfMapping.RdfMappingPackage.eINSTANCE);
		return result;
	}
}
