/*
 * generated by Xtext 2.14.0
 */
package com.zazuko.experimental.rmdsl.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class RdfMappingWebModule extends AbstractRdfMappingWebModule {
}
