/**
 * generated by Xtext 2.14.0
 */
package com.zazuko.experimental.rmdsl.tests;

import com.google.inject.Inject;
import com.zazuko.experimental.rmdsl.rdfMapping.Domainmodel;
import com.zazuko.experimental.rmdsl.tests.RdfMappingInjectorProvider;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(RdfMappingInjectorProvider.class)
@SuppressWarnings("all")
public class RdfMappingParsingTest {
  @Inject
  private ParseHelper<Domainmodel> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("vocabulary transit {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("prefix \"transit:\" \"http://vocab.org/transit/terms/\";\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("classes Stop;");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("properties route;\t\t");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      final Domainmodel result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
