/**
 * generated by Xtext 2.14.0
 */
package com.zazuko.experimental.rmdsl.rdfMapping;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Predicate Object Mapping</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.zazuko.experimental.rmdsl.rdfMapping.PredicateObjectMapping#getProperty <em>Property</em>}</li>
 *   <li>{@link com.zazuko.experimental.rmdsl.rdfMapping.PredicateObjectMapping#getTerm <em>Term</em>}</li>
 * </ul>
 *
 * @see com.zazuko.experimental.rmdsl.rdfMapping.RdfMappingPackage#getPredicateObjectMapping()
 * @model
 * @generated
 */
public interface PredicateObjectMapping extends EObject
{
  /**
   * Returns the value of the '<em><b>Property</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Property</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Property</em>' reference.
   * @see #setProperty(RdfProperty)
   * @see com.zazuko.experimental.rmdsl.rdfMapping.RdfMappingPackage#getPredicateObjectMapping_Property()
   * @model
   * @generated
   */
  RdfProperty getProperty();

  /**
   * Sets the value of the '{@link com.zazuko.experimental.rmdsl.rdfMapping.PredicateObjectMapping#getProperty <em>Property</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Property</em>' reference.
   * @see #getProperty()
   * @generated
   */
  void setProperty(RdfProperty value);

  /**
   * Returns the value of the '<em><b>Term</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Term</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Term</em>' containment reference.
   * @see #setTerm(ValuedTerm)
   * @see com.zazuko.experimental.rmdsl.rdfMapping.RdfMappingPackage#getPredicateObjectMapping_Term()
   * @model containment="true"
   * @generated
   */
  ValuedTerm getTerm();

  /**
   * Sets the value of the '{@link com.zazuko.experimental.rmdsl.rdfMapping.PredicateObjectMapping#getTerm <em>Term</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Term</em>' containment reference.
   * @see #getTerm()
   * @generated
   */
  void setTerm(ValuedTerm value);

} // PredicateObjectMapping
