/**
 * generated by Xtext 2.14.0
 */
package com.zazuko.experimental.rmdsl.rdfMapping;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.zazuko.experimental.rmdsl.rdfMapping.RdfMappingFactory
 * @model kind="package"
 * @generated
 */
public interface RdfMappingPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "rdfMapping";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.zazuko.com/experimental/rmdsl/RdfMapping";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "rdfMapping";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RdfMappingPackage eINSTANCE = com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl.init();

  /**
   * The meta object id for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.DomainmodelImpl <em>Domainmodel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.DomainmodelImpl
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getDomainmodel()
   * @generated
   */
  int DOMAINMODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAINMODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Domainmodel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAINMODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.ElementImpl
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 1;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.SourceTypesDefinitionImpl <em>Source Types Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.SourceTypesDefinitionImpl
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getSourceTypesDefinition()
   * @generated
   */
  int SOURCE_TYPES_DEFINITION = 2;

  /**
   * The feature id for the '<em><b>Types</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOURCE_TYPES_DEFINITION__TYPES = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Source Types Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOURCE_TYPES_DEFINITION_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.SourceTypeImpl <em>Source Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.SourceTypeImpl
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getSourceType()
   * @generated
   */
  int SOURCE_TYPE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOURCE_TYPE__NAME = 0;

  /**
   * The feature id for the '<em><b>Reference Formulation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOURCE_TYPE__REFERENCE_FORMULATION = 1;

  /**
   * The number of structural features of the '<em>Source Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOURCE_TYPE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.DatatypesDefinitionImpl <em>Datatypes Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.DatatypesDefinitionImpl
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getDatatypesDefinition()
   * @generated
   */
  int DATATYPES_DEFINITION = 4;

  /**
   * The feature id for the '<em><b>Prefix</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATATYPES_DEFINITION__PREFIX = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Types</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATATYPES_DEFINITION__TYPES = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Datatypes Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATATYPES_DEFINITION_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.DatatypeImpl <em>Datatype</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.DatatypeImpl
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getDatatype()
   * @generated
   */
  int DATATYPE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATATYPE__NAME = 0;

  /**
   * The number of structural features of the '<em>Datatype</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATATYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.LanguageTagDefinitionImpl <em>Language Tag Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.LanguageTagDefinitionImpl
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getLanguageTagDefinition()
   * @generated
   */
  int LANGUAGE_TAG_DEFINITION = 6;

  /**
   * The feature id for the '<em><b>Language Tags</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGE_TAG_DEFINITION__LANGUAGE_TAGS = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Language Tag Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGE_TAG_DEFINITION_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.LanguageTagImpl <em>Language Tag</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.LanguageTagImpl
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getLanguageTag()
   * @generated
   */
  int LANGUAGE_TAG = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGE_TAG__NAME = 0;

  /**
   * The number of structural features of the '<em>Language Tag</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGE_TAG_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.SourceGroupImpl <em>Source Group</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.SourceGroupImpl
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getSourceGroup()
   * @generated
   */
  int SOURCE_GROUP = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOURCE_GROUP__NAME = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOURCE_GROUP__TYPE = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOURCE_GROUP__SOURCE = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Logical Sources</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOURCE_GROUP__LOGICAL_SOURCES = ELEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Source Group</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOURCE_GROUP_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.LogicalSourceImpl <em>Logical Source</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.LogicalSourceImpl
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getLogicalSource()
   * @generated
   */
  int LOGICAL_SOURCE = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGICAL_SOURCE__NAME = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGICAL_SOURCE__TYPE = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGICAL_SOURCE__SOURCE = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Iterator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGICAL_SOURCE__ITERATOR = ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Referencables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGICAL_SOURCE__REFERENCABLES = ELEMENT_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Logical Source</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGICAL_SOURCE_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.ReferenceableImpl <em>Referenceable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.ReferenceableImpl
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getReferenceable()
   * @generated
   */
  int REFERENCEABLE = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCEABLE__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCEABLE__VALUE = 1;

  /**
   * The number of structural features of the '<em>Referenceable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCEABLE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.VocabularyImpl <em>Vocabulary</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.VocabularyImpl
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getVocabulary()
   * @generated
   */
  int VOCABULARY = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VOCABULARY__NAME = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Prefix</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VOCABULARY__PREFIX = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Classes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VOCABULARY__CLASSES = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VOCABULARY__PROPERTIES = ELEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Vocabulary</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VOCABULARY_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.PrefixImpl <em>Prefix</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.PrefixImpl
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getPrefix()
   * @generated
   */
  int PREFIX = 12;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREFIX__LABEL = 0;

  /**
   * The feature id for the '<em><b>Iri</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREFIX__IRI = 1;

  /**
   * The number of structural features of the '<em>Prefix</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREFIX_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfPropertyImpl <em>Rdf Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfPropertyImpl
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getRdfProperty()
   * @generated
   */
  int RDF_PROPERTY = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RDF_PROPERTY__NAME = 0;

  /**
   * The number of structural features of the '<em>Rdf Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RDF_PROPERTY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfClassImpl <em>Rdf Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfClassImpl
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getRdfClass()
   * @generated
   */
  int RDF_CLASS = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RDF_CLASS__NAME = 0;

  /**
   * The number of structural features of the '<em>Rdf Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RDF_CLASS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.MappingImpl <em>Mapping</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.MappingImpl
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getMapping()
   * @generated
   */
  int MAPPING = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAPPING__NAME = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAPPING__SOURCE = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Pattern</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAPPING__PATTERN = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAPPING__REFERENCE = ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Subject Type Mappings</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAPPING__SUBJECT_TYPE_MAPPINGS = ELEMENT_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Po Mappings</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAPPING__PO_MAPPINGS = ELEMENT_FEATURE_COUNT + 5;

  /**
   * The number of structural features of the '<em>Mapping</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAPPING_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 6;

  /**
   * The meta object id for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.SubjectTypeMappingImpl <em>Subject Type Mapping</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.SubjectTypeMappingImpl
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getSubjectTypeMapping()
   * @generated
   */
  int SUBJECT_TYPE_MAPPING = 16;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBJECT_TYPE_MAPPING__TYPE = 0;

  /**
   * The number of structural features of the '<em>Subject Type Mapping</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBJECT_TYPE_MAPPING_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.PredicateObjectMappingImpl <em>Predicate Object Mapping</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.PredicateObjectMappingImpl
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getPredicateObjectMapping()
   * @generated
   */
  int PREDICATE_OBJECT_MAPPING = 17;

  /**
   * The feature id for the '<em><b>Property</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_OBJECT_MAPPING__PROPERTY = 0;

  /**
   * The feature id for the '<em><b>Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_OBJECT_MAPPING__REFERENCE = 1;

  /**
   * The feature id for the '<em><b>Datatype</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_OBJECT_MAPPING__DATATYPE = 2;

  /**
   * The feature id for the '<em><b>Language Tag</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_OBJECT_MAPPING__LANGUAGE_TAG = 3;

  /**
   * The number of structural features of the '<em>Predicate Object Mapping</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_OBJECT_MAPPING_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.ImportImpl <em>Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.ImportImpl
   * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getImport()
   * @generated
   */
  int IMPORT = 18;

  /**
   * The feature id for the '<em><b>Imported Namespace</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__IMPORTED_NAMESPACE = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link com.zazuko.experimental.rmdsl.rdfMapping.Domainmodel <em>Domainmodel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Domainmodel</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.Domainmodel
   * @generated
   */
  EClass getDomainmodel();

  /**
   * Returns the meta object for the containment reference list '{@link com.zazuko.experimental.rmdsl.rdfMapping.Domainmodel#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.Domainmodel#getElements()
   * @see #getDomainmodel()
   * @generated
   */
  EReference getDomainmodel_Elements();

  /**
   * Returns the meta object for class '{@link com.zazuko.experimental.rmdsl.rdfMapping.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for class '{@link com.zazuko.experimental.rmdsl.rdfMapping.SourceTypesDefinition <em>Source Types Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Source Types Definition</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.SourceTypesDefinition
   * @generated
   */
  EClass getSourceTypesDefinition();

  /**
   * Returns the meta object for the containment reference list '{@link com.zazuko.experimental.rmdsl.rdfMapping.SourceTypesDefinition#getTypes <em>Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Types</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.SourceTypesDefinition#getTypes()
   * @see #getSourceTypesDefinition()
   * @generated
   */
  EReference getSourceTypesDefinition_Types();

  /**
   * Returns the meta object for class '{@link com.zazuko.experimental.rmdsl.rdfMapping.SourceType <em>Source Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Source Type</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.SourceType
   * @generated
   */
  EClass getSourceType();

  /**
   * Returns the meta object for the attribute '{@link com.zazuko.experimental.rmdsl.rdfMapping.SourceType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.SourceType#getName()
   * @see #getSourceType()
   * @generated
   */
  EAttribute getSourceType_Name();

  /**
   * Returns the meta object for the attribute '{@link com.zazuko.experimental.rmdsl.rdfMapping.SourceType#getReferenceFormulation <em>Reference Formulation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Reference Formulation</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.SourceType#getReferenceFormulation()
   * @see #getSourceType()
   * @generated
   */
  EAttribute getSourceType_ReferenceFormulation();

  /**
   * Returns the meta object for class '{@link com.zazuko.experimental.rmdsl.rdfMapping.DatatypesDefinition <em>Datatypes Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Datatypes Definition</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.DatatypesDefinition
   * @generated
   */
  EClass getDatatypesDefinition();

  /**
   * Returns the meta object for the containment reference '{@link com.zazuko.experimental.rmdsl.rdfMapping.DatatypesDefinition#getPrefix <em>Prefix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Prefix</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.DatatypesDefinition#getPrefix()
   * @see #getDatatypesDefinition()
   * @generated
   */
  EReference getDatatypesDefinition_Prefix();

  /**
   * Returns the meta object for the containment reference list '{@link com.zazuko.experimental.rmdsl.rdfMapping.DatatypesDefinition#getTypes <em>Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Types</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.DatatypesDefinition#getTypes()
   * @see #getDatatypesDefinition()
   * @generated
   */
  EReference getDatatypesDefinition_Types();

  /**
   * Returns the meta object for class '{@link com.zazuko.experimental.rmdsl.rdfMapping.Datatype <em>Datatype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Datatype</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.Datatype
   * @generated
   */
  EClass getDatatype();

  /**
   * Returns the meta object for the attribute '{@link com.zazuko.experimental.rmdsl.rdfMapping.Datatype#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.Datatype#getName()
   * @see #getDatatype()
   * @generated
   */
  EAttribute getDatatype_Name();

  /**
   * Returns the meta object for class '{@link com.zazuko.experimental.rmdsl.rdfMapping.LanguageTagDefinition <em>Language Tag Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Language Tag Definition</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.LanguageTagDefinition
   * @generated
   */
  EClass getLanguageTagDefinition();

  /**
   * Returns the meta object for the containment reference list '{@link com.zazuko.experimental.rmdsl.rdfMapping.LanguageTagDefinition#getLanguageTags <em>Language Tags</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Language Tags</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.LanguageTagDefinition#getLanguageTags()
   * @see #getLanguageTagDefinition()
   * @generated
   */
  EReference getLanguageTagDefinition_LanguageTags();

  /**
   * Returns the meta object for class '{@link com.zazuko.experimental.rmdsl.rdfMapping.LanguageTag <em>Language Tag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Language Tag</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.LanguageTag
   * @generated
   */
  EClass getLanguageTag();

  /**
   * Returns the meta object for the attribute '{@link com.zazuko.experimental.rmdsl.rdfMapping.LanguageTag#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.LanguageTag#getName()
   * @see #getLanguageTag()
   * @generated
   */
  EAttribute getLanguageTag_Name();

  /**
   * Returns the meta object for class '{@link com.zazuko.experimental.rmdsl.rdfMapping.SourceGroup <em>Source Group</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Source Group</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.SourceGroup
   * @generated
   */
  EClass getSourceGroup();

  /**
   * Returns the meta object for the attribute '{@link com.zazuko.experimental.rmdsl.rdfMapping.SourceGroup#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.SourceGroup#getName()
   * @see #getSourceGroup()
   * @generated
   */
  EAttribute getSourceGroup_Name();

  /**
   * Returns the meta object for the reference '{@link com.zazuko.experimental.rmdsl.rdfMapping.SourceGroup#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.SourceGroup#getType()
   * @see #getSourceGroup()
   * @generated
   */
  EReference getSourceGroup_Type();

  /**
   * Returns the meta object for the attribute '{@link com.zazuko.experimental.rmdsl.rdfMapping.SourceGroup#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Source</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.SourceGroup#getSource()
   * @see #getSourceGroup()
   * @generated
   */
  EAttribute getSourceGroup_Source();

  /**
   * Returns the meta object for the containment reference list '{@link com.zazuko.experimental.rmdsl.rdfMapping.SourceGroup#getLogicalSources <em>Logical Sources</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Logical Sources</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.SourceGroup#getLogicalSources()
   * @see #getSourceGroup()
   * @generated
   */
  EReference getSourceGroup_LogicalSources();

  /**
   * Returns the meta object for class '{@link com.zazuko.experimental.rmdsl.rdfMapping.LogicalSource <em>Logical Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Logical Source</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.LogicalSource
   * @generated
   */
  EClass getLogicalSource();

  /**
   * Returns the meta object for the attribute '{@link com.zazuko.experimental.rmdsl.rdfMapping.LogicalSource#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.LogicalSource#getName()
   * @see #getLogicalSource()
   * @generated
   */
  EAttribute getLogicalSource_Name();

  /**
   * Returns the meta object for the reference '{@link com.zazuko.experimental.rmdsl.rdfMapping.LogicalSource#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.LogicalSource#getType()
   * @see #getLogicalSource()
   * @generated
   */
  EReference getLogicalSource_Type();

  /**
   * Returns the meta object for the attribute '{@link com.zazuko.experimental.rmdsl.rdfMapping.LogicalSource#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Source</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.LogicalSource#getSource()
   * @see #getLogicalSource()
   * @generated
   */
  EAttribute getLogicalSource_Source();

  /**
   * Returns the meta object for the attribute '{@link com.zazuko.experimental.rmdsl.rdfMapping.LogicalSource#getIterator <em>Iterator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Iterator</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.LogicalSource#getIterator()
   * @see #getLogicalSource()
   * @generated
   */
  EAttribute getLogicalSource_Iterator();

  /**
   * Returns the meta object for the containment reference list '{@link com.zazuko.experimental.rmdsl.rdfMapping.LogicalSource#getReferencables <em>Referencables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Referencables</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.LogicalSource#getReferencables()
   * @see #getLogicalSource()
   * @generated
   */
  EReference getLogicalSource_Referencables();

  /**
   * Returns the meta object for class '{@link com.zazuko.experimental.rmdsl.rdfMapping.Referenceable <em>Referenceable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Referenceable</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.Referenceable
   * @generated
   */
  EClass getReferenceable();

  /**
   * Returns the meta object for the attribute '{@link com.zazuko.experimental.rmdsl.rdfMapping.Referenceable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.Referenceable#getName()
   * @see #getReferenceable()
   * @generated
   */
  EAttribute getReferenceable_Name();

  /**
   * Returns the meta object for the attribute '{@link com.zazuko.experimental.rmdsl.rdfMapping.Referenceable#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.Referenceable#getValue()
   * @see #getReferenceable()
   * @generated
   */
  EAttribute getReferenceable_Value();

  /**
   * Returns the meta object for class '{@link com.zazuko.experimental.rmdsl.rdfMapping.Vocabulary <em>Vocabulary</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vocabulary</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.Vocabulary
   * @generated
   */
  EClass getVocabulary();

  /**
   * Returns the meta object for the attribute '{@link com.zazuko.experimental.rmdsl.rdfMapping.Vocabulary#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.Vocabulary#getName()
   * @see #getVocabulary()
   * @generated
   */
  EAttribute getVocabulary_Name();

  /**
   * Returns the meta object for the containment reference '{@link com.zazuko.experimental.rmdsl.rdfMapping.Vocabulary#getPrefix <em>Prefix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Prefix</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.Vocabulary#getPrefix()
   * @see #getVocabulary()
   * @generated
   */
  EReference getVocabulary_Prefix();

  /**
   * Returns the meta object for the containment reference list '{@link com.zazuko.experimental.rmdsl.rdfMapping.Vocabulary#getClasses <em>Classes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Classes</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.Vocabulary#getClasses()
   * @see #getVocabulary()
   * @generated
   */
  EReference getVocabulary_Classes();

  /**
   * Returns the meta object for the containment reference list '{@link com.zazuko.experimental.rmdsl.rdfMapping.Vocabulary#getProperties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Properties</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.Vocabulary#getProperties()
   * @see #getVocabulary()
   * @generated
   */
  EReference getVocabulary_Properties();

  /**
   * Returns the meta object for class '{@link com.zazuko.experimental.rmdsl.rdfMapping.Prefix <em>Prefix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Prefix</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.Prefix
   * @generated
   */
  EClass getPrefix();

  /**
   * Returns the meta object for the attribute '{@link com.zazuko.experimental.rmdsl.rdfMapping.Prefix#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.Prefix#getLabel()
   * @see #getPrefix()
   * @generated
   */
  EAttribute getPrefix_Label();

  /**
   * Returns the meta object for the attribute '{@link com.zazuko.experimental.rmdsl.rdfMapping.Prefix#getIri <em>Iri</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Iri</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.Prefix#getIri()
   * @see #getPrefix()
   * @generated
   */
  EAttribute getPrefix_Iri();

  /**
   * Returns the meta object for class '{@link com.zazuko.experimental.rmdsl.rdfMapping.RdfProperty <em>Rdf Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rdf Property</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.RdfProperty
   * @generated
   */
  EClass getRdfProperty();

  /**
   * Returns the meta object for the attribute '{@link com.zazuko.experimental.rmdsl.rdfMapping.RdfProperty#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.RdfProperty#getName()
   * @see #getRdfProperty()
   * @generated
   */
  EAttribute getRdfProperty_Name();

  /**
   * Returns the meta object for class '{@link com.zazuko.experimental.rmdsl.rdfMapping.RdfClass <em>Rdf Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rdf Class</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.RdfClass
   * @generated
   */
  EClass getRdfClass();

  /**
   * Returns the meta object for the attribute '{@link com.zazuko.experimental.rmdsl.rdfMapping.RdfClass#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.RdfClass#getName()
   * @see #getRdfClass()
   * @generated
   */
  EAttribute getRdfClass_Name();

  /**
   * Returns the meta object for class '{@link com.zazuko.experimental.rmdsl.rdfMapping.Mapping <em>Mapping</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mapping</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.Mapping
   * @generated
   */
  EClass getMapping();

  /**
   * Returns the meta object for the attribute '{@link com.zazuko.experimental.rmdsl.rdfMapping.Mapping#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.Mapping#getName()
   * @see #getMapping()
   * @generated
   */
  EAttribute getMapping_Name();

  /**
   * Returns the meta object for the reference '{@link com.zazuko.experimental.rmdsl.rdfMapping.Mapping#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Source</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.Mapping#getSource()
   * @see #getMapping()
   * @generated
   */
  EReference getMapping_Source();

  /**
   * Returns the meta object for the attribute '{@link com.zazuko.experimental.rmdsl.rdfMapping.Mapping#getPattern <em>Pattern</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pattern</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.Mapping#getPattern()
   * @see #getMapping()
   * @generated
   */
  EAttribute getMapping_Pattern();

  /**
   * Returns the meta object for the reference '{@link com.zazuko.experimental.rmdsl.rdfMapping.Mapping#getReference <em>Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Reference</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.Mapping#getReference()
   * @see #getMapping()
   * @generated
   */
  EReference getMapping_Reference();

  /**
   * Returns the meta object for the containment reference list '{@link com.zazuko.experimental.rmdsl.rdfMapping.Mapping#getSubjectTypeMappings <em>Subject Type Mappings</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Subject Type Mappings</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.Mapping#getSubjectTypeMappings()
   * @see #getMapping()
   * @generated
   */
  EReference getMapping_SubjectTypeMappings();

  /**
   * Returns the meta object for the containment reference list '{@link com.zazuko.experimental.rmdsl.rdfMapping.Mapping#getPoMappings <em>Po Mappings</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Po Mappings</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.Mapping#getPoMappings()
   * @see #getMapping()
   * @generated
   */
  EReference getMapping_PoMappings();

  /**
   * Returns the meta object for class '{@link com.zazuko.experimental.rmdsl.rdfMapping.SubjectTypeMapping <em>Subject Type Mapping</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Subject Type Mapping</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.SubjectTypeMapping
   * @generated
   */
  EClass getSubjectTypeMapping();

  /**
   * Returns the meta object for the reference '{@link com.zazuko.experimental.rmdsl.rdfMapping.SubjectTypeMapping#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.SubjectTypeMapping#getType()
   * @see #getSubjectTypeMapping()
   * @generated
   */
  EReference getSubjectTypeMapping_Type();

  /**
   * Returns the meta object for class '{@link com.zazuko.experimental.rmdsl.rdfMapping.PredicateObjectMapping <em>Predicate Object Mapping</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Predicate Object Mapping</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.PredicateObjectMapping
   * @generated
   */
  EClass getPredicateObjectMapping();

  /**
   * Returns the meta object for the reference '{@link com.zazuko.experimental.rmdsl.rdfMapping.PredicateObjectMapping#getProperty <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Property</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.PredicateObjectMapping#getProperty()
   * @see #getPredicateObjectMapping()
   * @generated
   */
  EReference getPredicateObjectMapping_Property();

  /**
   * Returns the meta object for the reference '{@link com.zazuko.experimental.rmdsl.rdfMapping.PredicateObjectMapping#getReference <em>Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Reference</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.PredicateObjectMapping#getReference()
   * @see #getPredicateObjectMapping()
   * @generated
   */
  EReference getPredicateObjectMapping_Reference();

  /**
   * Returns the meta object for the reference '{@link com.zazuko.experimental.rmdsl.rdfMapping.PredicateObjectMapping#getDatatype <em>Datatype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Datatype</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.PredicateObjectMapping#getDatatype()
   * @see #getPredicateObjectMapping()
   * @generated
   */
  EReference getPredicateObjectMapping_Datatype();

  /**
   * Returns the meta object for the reference '{@link com.zazuko.experimental.rmdsl.rdfMapping.PredicateObjectMapping#getLanguageTag <em>Language Tag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Language Tag</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.PredicateObjectMapping#getLanguageTag()
   * @see #getPredicateObjectMapping()
   * @generated
   */
  EReference getPredicateObjectMapping_LanguageTag();

  /**
   * Returns the meta object for class '{@link com.zazuko.experimental.rmdsl.rdfMapping.Import <em>Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.Import
   * @generated
   */
  EClass getImport();

  /**
   * Returns the meta object for the attribute '{@link com.zazuko.experimental.rmdsl.rdfMapping.Import#getImportedNamespace <em>Imported Namespace</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Imported Namespace</em>'.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.Import#getImportedNamespace()
   * @see #getImport()
   * @generated
   */
  EAttribute getImport_ImportedNamespace();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  RdfMappingFactory getRdfMappingFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.DomainmodelImpl <em>Domainmodel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.DomainmodelImpl
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getDomainmodel()
     * @generated
     */
    EClass DOMAINMODEL = eINSTANCE.getDomainmodel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOMAINMODEL__ELEMENTS = eINSTANCE.getDomainmodel_Elements();

    /**
     * The meta object literal for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.ElementImpl
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.SourceTypesDefinitionImpl <em>Source Types Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.SourceTypesDefinitionImpl
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getSourceTypesDefinition()
     * @generated
     */
    EClass SOURCE_TYPES_DEFINITION = eINSTANCE.getSourceTypesDefinition();

    /**
     * The meta object literal for the '<em><b>Types</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SOURCE_TYPES_DEFINITION__TYPES = eINSTANCE.getSourceTypesDefinition_Types();

    /**
     * The meta object literal for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.SourceTypeImpl <em>Source Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.SourceTypeImpl
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getSourceType()
     * @generated
     */
    EClass SOURCE_TYPE = eINSTANCE.getSourceType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SOURCE_TYPE__NAME = eINSTANCE.getSourceType_Name();

    /**
     * The meta object literal for the '<em><b>Reference Formulation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SOURCE_TYPE__REFERENCE_FORMULATION = eINSTANCE.getSourceType_ReferenceFormulation();

    /**
     * The meta object literal for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.DatatypesDefinitionImpl <em>Datatypes Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.DatatypesDefinitionImpl
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getDatatypesDefinition()
     * @generated
     */
    EClass DATATYPES_DEFINITION = eINSTANCE.getDatatypesDefinition();

    /**
     * The meta object literal for the '<em><b>Prefix</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATATYPES_DEFINITION__PREFIX = eINSTANCE.getDatatypesDefinition_Prefix();

    /**
     * The meta object literal for the '<em><b>Types</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATATYPES_DEFINITION__TYPES = eINSTANCE.getDatatypesDefinition_Types();

    /**
     * The meta object literal for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.DatatypeImpl <em>Datatype</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.DatatypeImpl
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getDatatype()
     * @generated
     */
    EClass DATATYPE = eINSTANCE.getDatatype();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATATYPE__NAME = eINSTANCE.getDatatype_Name();

    /**
     * The meta object literal for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.LanguageTagDefinitionImpl <em>Language Tag Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.LanguageTagDefinitionImpl
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getLanguageTagDefinition()
     * @generated
     */
    EClass LANGUAGE_TAG_DEFINITION = eINSTANCE.getLanguageTagDefinition();

    /**
     * The meta object literal for the '<em><b>Language Tags</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LANGUAGE_TAG_DEFINITION__LANGUAGE_TAGS = eINSTANCE.getLanguageTagDefinition_LanguageTags();

    /**
     * The meta object literal for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.LanguageTagImpl <em>Language Tag</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.LanguageTagImpl
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getLanguageTag()
     * @generated
     */
    EClass LANGUAGE_TAG = eINSTANCE.getLanguageTag();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LANGUAGE_TAG__NAME = eINSTANCE.getLanguageTag_Name();

    /**
     * The meta object literal for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.SourceGroupImpl <em>Source Group</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.SourceGroupImpl
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getSourceGroup()
     * @generated
     */
    EClass SOURCE_GROUP = eINSTANCE.getSourceGroup();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SOURCE_GROUP__NAME = eINSTANCE.getSourceGroup_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SOURCE_GROUP__TYPE = eINSTANCE.getSourceGroup_Type();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SOURCE_GROUP__SOURCE = eINSTANCE.getSourceGroup_Source();

    /**
     * The meta object literal for the '<em><b>Logical Sources</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SOURCE_GROUP__LOGICAL_SOURCES = eINSTANCE.getSourceGroup_LogicalSources();

    /**
     * The meta object literal for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.LogicalSourceImpl <em>Logical Source</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.LogicalSourceImpl
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getLogicalSource()
     * @generated
     */
    EClass LOGICAL_SOURCE = eINSTANCE.getLogicalSource();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOGICAL_SOURCE__NAME = eINSTANCE.getLogicalSource_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOGICAL_SOURCE__TYPE = eINSTANCE.getLogicalSource_Type();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOGICAL_SOURCE__SOURCE = eINSTANCE.getLogicalSource_Source();

    /**
     * The meta object literal for the '<em><b>Iterator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOGICAL_SOURCE__ITERATOR = eINSTANCE.getLogicalSource_Iterator();

    /**
     * The meta object literal for the '<em><b>Referencables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOGICAL_SOURCE__REFERENCABLES = eINSTANCE.getLogicalSource_Referencables();

    /**
     * The meta object literal for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.ReferenceableImpl <em>Referenceable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.ReferenceableImpl
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getReferenceable()
     * @generated
     */
    EClass REFERENCEABLE = eINSTANCE.getReferenceable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REFERENCEABLE__NAME = eINSTANCE.getReferenceable_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REFERENCEABLE__VALUE = eINSTANCE.getReferenceable_Value();

    /**
     * The meta object literal for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.VocabularyImpl <em>Vocabulary</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.VocabularyImpl
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getVocabulary()
     * @generated
     */
    EClass VOCABULARY = eINSTANCE.getVocabulary();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VOCABULARY__NAME = eINSTANCE.getVocabulary_Name();

    /**
     * The meta object literal for the '<em><b>Prefix</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VOCABULARY__PREFIX = eINSTANCE.getVocabulary_Prefix();

    /**
     * The meta object literal for the '<em><b>Classes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VOCABULARY__CLASSES = eINSTANCE.getVocabulary_Classes();

    /**
     * The meta object literal for the '<em><b>Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VOCABULARY__PROPERTIES = eINSTANCE.getVocabulary_Properties();

    /**
     * The meta object literal for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.PrefixImpl <em>Prefix</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.PrefixImpl
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getPrefix()
     * @generated
     */
    EClass PREFIX = eINSTANCE.getPrefix();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREFIX__LABEL = eINSTANCE.getPrefix_Label();

    /**
     * The meta object literal for the '<em><b>Iri</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREFIX__IRI = eINSTANCE.getPrefix_Iri();

    /**
     * The meta object literal for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfPropertyImpl <em>Rdf Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfPropertyImpl
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getRdfProperty()
     * @generated
     */
    EClass RDF_PROPERTY = eINSTANCE.getRdfProperty();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RDF_PROPERTY__NAME = eINSTANCE.getRdfProperty_Name();

    /**
     * The meta object literal for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfClassImpl <em>Rdf Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfClassImpl
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getRdfClass()
     * @generated
     */
    EClass RDF_CLASS = eINSTANCE.getRdfClass();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RDF_CLASS__NAME = eINSTANCE.getRdfClass_Name();

    /**
     * The meta object literal for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.MappingImpl <em>Mapping</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.MappingImpl
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getMapping()
     * @generated
     */
    EClass MAPPING = eINSTANCE.getMapping();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAPPING__NAME = eINSTANCE.getMapping_Name();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAPPING__SOURCE = eINSTANCE.getMapping_Source();

    /**
     * The meta object literal for the '<em><b>Pattern</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAPPING__PATTERN = eINSTANCE.getMapping_Pattern();

    /**
     * The meta object literal for the '<em><b>Reference</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAPPING__REFERENCE = eINSTANCE.getMapping_Reference();

    /**
     * The meta object literal for the '<em><b>Subject Type Mappings</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAPPING__SUBJECT_TYPE_MAPPINGS = eINSTANCE.getMapping_SubjectTypeMappings();

    /**
     * The meta object literal for the '<em><b>Po Mappings</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAPPING__PO_MAPPINGS = eINSTANCE.getMapping_PoMappings();

    /**
     * The meta object literal for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.SubjectTypeMappingImpl <em>Subject Type Mapping</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.SubjectTypeMappingImpl
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getSubjectTypeMapping()
     * @generated
     */
    EClass SUBJECT_TYPE_MAPPING = eINSTANCE.getSubjectTypeMapping();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUBJECT_TYPE_MAPPING__TYPE = eINSTANCE.getSubjectTypeMapping_Type();

    /**
     * The meta object literal for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.PredicateObjectMappingImpl <em>Predicate Object Mapping</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.PredicateObjectMappingImpl
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getPredicateObjectMapping()
     * @generated
     */
    EClass PREDICATE_OBJECT_MAPPING = eINSTANCE.getPredicateObjectMapping();

    /**
     * The meta object literal for the '<em><b>Property</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE_OBJECT_MAPPING__PROPERTY = eINSTANCE.getPredicateObjectMapping_Property();

    /**
     * The meta object literal for the '<em><b>Reference</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE_OBJECT_MAPPING__REFERENCE = eINSTANCE.getPredicateObjectMapping_Reference();

    /**
     * The meta object literal for the '<em><b>Datatype</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE_OBJECT_MAPPING__DATATYPE = eINSTANCE.getPredicateObjectMapping_Datatype();

    /**
     * The meta object literal for the '<em><b>Language Tag</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE_OBJECT_MAPPING__LANGUAGE_TAG = eINSTANCE.getPredicateObjectMapping_LanguageTag();

    /**
     * The meta object literal for the '{@link com.zazuko.experimental.rmdsl.rdfMapping.impl.ImportImpl <em>Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.ImportImpl
     * @see com.zazuko.experimental.rmdsl.rdfMapping.impl.RdfMappingPackageImpl#getImport()
     * @generated
     */
    EClass IMPORT = eINSTANCE.getImport();

    /**
     * The meta object literal for the '<em><b>Imported Namespace</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT__IMPORTED_NAMESPACE = eINSTANCE.getImport_ImportedNamespace();

  }

} //RdfMappingPackage
