/**
 * generated by Xtext 2.14.0
 */
package com.zazuko.experimental.rmdsl.rdfMapping;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reference Valued Term</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.zazuko.experimental.rmdsl.rdfMapping.ReferenceValuedTerm#getDatatype <em>Datatype</em>}</li>
 *   <li>{@link com.zazuko.experimental.rmdsl.rdfMapping.ReferenceValuedTerm#getLanguageTag <em>Language Tag</em>}</li>
 * </ul>
 *
 * @see com.zazuko.experimental.rmdsl.rdfMapping.RdfMappingPackage#getReferenceValuedTerm()
 * @model
 * @generated
 */
public interface ReferenceValuedTerm extends ValuedTerm
{
  /**
   * Returns the value of the '<em><b>Datatype</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Datatype</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Datatype</em>' reference.
   * @see #setDatatype(Datatype)
   * @see com.zazuko.experimental.rmdsl.rdfMapping.RdfMappingPackage#getReferenceValuedTerm_Datatype()
   * @model
   * @generated
   */
  Datatype getDatatype();

  /**
   * Sets the value of the '{@link com.zazuko.experimental.rmdsl.rdfMapping.ReferenceValuedTerm#getDatatype <em>Datatype</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Datatype</em>' reference.
   * @see #getDatatype()
   * @generated
   */
  void setDatatype(Datatype value);

  /**
   * Returns the value of the '<em><b>Language Tag</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Language Tag</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Language Tag</em>' reference.
   * @see #setLanguageTag(LanguageTag)
   * @see com.zazuko.experimental.rmdsl.rdfMapping.RdfMappingPackage#getReferenceValuedTerm_LanguageTag()
   * @model
   * @generated
   */
  LanguageTag getLanguageTag();

  /**
   * Sets the value of the '{@link com.zazuko.experimental.rmdsl.rdfMapping.ReferenceValuedTerm#getLanguageTag <em>Language Tag</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Language Tag</em>' reference.
   * @see #getLanguageTag()
   * @generated
   */
  void setLanguageTag(LanguageTag value);

} // ReferenceValuedTerm
