/**
 * generated by Xtext 2.14.0
 */
package com.zazuko.experimental.rmdsl.rdfMapping;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Valued Term</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.zazuko.experimental.rmdsl.rdfMapping.RdfMappingPackage#getValuedTerm()
 * @model
 * @generated
 */
public interface ValuedTerm extends EObject
{
} // ValuedTerm
