/**
 * generated by Xtext 2.14.0
 */
package com.zazuko.experimental.rmdsl.rdfMapping;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Vocabulary</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.zazuko.experimental.rmdsl.rdfMapping.Vocabulary#getName <em>Name</em>}</li>
 *   <li>{@link com.zazuko.experimental.rmdsl.rdfMapping.Vocabulary#getPrefix <em>Prefix</em>}</li>
 *   <li>{@link com.zazuko.experimental.rmdsl.rdfMapping.Vocabulary#getClasses <em>Classes</em>}</li>
 *   <li>{@link com.zazuko.experimental.rmdsl.rdfMapping.Vocabulary#getProperties <em>Properties</em>}</li>
 * </ul>
 *
 * @see com.zazuko.experimental.rmdsl.rdfMapping.RdfMappingPackage#getVocabulary()
 * @model
 * @generated
 */
public interface Vocabulary extends Element
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.zazuko.experimental.rmdsl.rdfMapping.RdfMappingPackage#getVocabulary_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.zazuko.experimental.rmdsl.rdfMapping.Vocabulary#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Prefix</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Prefix</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prefix</em>' containment reference.
   * @see #setPrefix(Prefix)
   * @see com.zazuko.experimental.rmdsl.rdfMapping.RdfMappingPackage#getVocabulary_Prefix()
   * @model containment="true"
   * @generated
   */
  Prefix getPrefix();

  /**
   * Sets the value of the '{@link com.zazuko.experimental.rmdsl.rdfMapping.Vocabulary#getPrefix <em>Prefix</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prefix</em>' containment reference.
   * @see #getPrefix()
   * @generated
   */
  void setPrefix(Prefix value);

  /**
   * Returns the value of the '<em><b>Classes</b></em>' containment reference list.
   * The list contents are of type {@link com.zazuko.experimental.rmdsl.rdfMapping.RdfClass}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Classes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Classes</em>' containment reference list.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.RdfMappingPackage#getVocabulary_Classes()
   * @model containment="true"
   * @generated
   */
  EList<RdfClass> getClasses();

  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link com.zazuko.experimental.rmdsl.rdfMapping.RdfProperty}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Properties</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see com.zazuko.experimental.rmdsl.rdfMapping.RdfMappingPackage#getVocabulary_Properties()
   * @model containment="true"
   * @generated
   */
  EList<RdfProperty> getProperties();

} // Vocabulary
