/**
 * generated by Xtext 2.14.0
 */
package com.zazuko.experimental.rmdsl.ide;

import com.zazuko.experimental.rmdsl.ide.AbstractRdfMappingIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RdfMappingIdeModule extends AbstractRdfMappingIdeModule {
}
