/**
 * generated by Xtext 2.14.0
 */
package com.zazuko.experimental.rmdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.zazuko.experimental.rmdsl.RdfMappingRuntimeModule;
import com.zazuko.experimental.rmdsl.RdfMappingStandaloneSetup;
import com.zazuko.experimental.rmdsl.ide.RdfMappingIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class RdfMappingIdeSetup extends RdfMappingStandaloneSetup {
  @Override
  public Injector createInjector() {
    RdfMappingRuntimeModule _rdfMappingRuntimeModule = new RdfMappingRuntimeModule();
    RdfMappingIdeModule _rdfMappingIdeModule = new RdfMappingIdeModule();
    return Guice.createInjector(Modules2.mixin(_rdfMappingRuntimeModule, _rdfMappingIdeModule));
  }
}
