/**
 * generated by Xtext 2.14.0
 */
package com.zazuko.experimental.rmdsl.ui;

import com.zazuko.experimental.rmdsl.ui.AbstractRdfMappingUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class RdfMappingUiModule extends AbstractRdfMappingUiModule {
  public RdfMappingUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
