/*
 * generated by Xtext 2.14.0
 */
package com.zazuko.experimental.rmdsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class RdfMappingGrammarAccess extends AbstractGrammarElementFinder {
	
	public class DomainmodelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.zazuko.experimental.rmdsl.RdfMapping.Domainmodel");
		private final Assignment cElementsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cElementsElementParserRuleCall_0 = (RuleCall)cElementsAssignment.eContents().get(0);
		
		//Domainmodel:
		//	elements+=Element*;
		@Override public ParserRule getRule() { return rule; }
		
		//elements+=Element*
		public Assignment getElementsAssignment() { return cElementsAssignment; }
		
		//Element
		public RuleCall getElementsElementParserRuleCall_0() { return cElementsElementParserRuleCall_0; }
	}
	public class ElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.zazuko.experimental.rmdsl.RdfMapping.Element");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cImportParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSourceTypesDefinitionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cSourceGroupParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cLogicalSourceParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cVocabularyParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cMappingParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		
		//Element:
		//	Import | SourceTypesDefinition | SourceGroup | LogicalSource | Vocabulary | Mapping;
		@Override public ParserRule getRule() { return rule; }
		
		//Import | SourceTypesDefinition | SourceGroup | LogicalSource | Vocabulary | Mapping
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Import
		public RuleCall getImportParserRuleCall_0() { return cImportParserRuleCall_0; }
		
		//SourceTypesDefinition
		public RuleCall getSourceTypesDefinitionParserRuleCall_1() { return cSourceTypesDefinitionParserRuleCall_1; }
		
		//SourceGroup
		public RuleCall getSourceGroupParserRuleCall_2() { return cSourceGroupParserRuleCall_2; }
		
		//LogicalSource
		public RuleCall getLogicalSourceParserRuleCall_3() { return cLogicalSourceParserRuleCall_3; }
		
		//Vocabulary
		public RuleCall getVocabularyParserRuleCall_4() { return cVocabularyParserRuleCall_4; }
		
		//Mapping
		public RuleCall getMappingParserRuleCall_5() { return cMappingParserRuleCall_5; }
	}
	public class SourceTypesDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.zazuko.experimental.rmdsl.RdfMapping.SourceTypesDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSourceTypesDefinitionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSourceTypesKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTypesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTypesSourceTypeParserRuleCall_3_0 = (RuleCall)cTypesAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//SourceTypesDefinition:
		//	{SourceTypesDefinition}
		//	'source-types' '{'
		//	types+=SourceType*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{SourceTypesDefinition} 'source-types' '{' types+=SourceType* '}'
		public Group getGroup() { return cGroup; }
		
		//{SourceTypesDefinition}
		public Action getSourceTypesDefinitionAction_0() { return cSourceTypesDefinitionAction_0; }
		
		//'source-types'
		public Keyword getSourceTypesKeyword_1() { return cSourceTypesKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//types+=SourceType*
		public Assignment getTypesAssignment_3() { return cTypesAssignment_3; }
		
		//SourceType
		public RuleCall getTypesSourceTypeParserRuleCall_3_0() { return cTypesSourceTypeParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class SourceTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.zazuko.experimental.rmdsl.RdfMapping.SourceType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cReferenceFormulationKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cReferenceFormulationAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cReferenceFormulationSTRINGTerminalRuleCall_2_0 = (RuleCall)cReferenceFormulationAssignment_2.eContents().get(0);
		
		//SourceType:
		//	name=ID 'referenceFormulation' referenceFormulation=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID 'referenceFormulation' referenceFormulation=STRING
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//'referenceFormulation'
		public Keyword getReferenceFormulationKeyword_1() { return cReferenceFormulationKeyword_1; }
		
		//referenceFormulation=STRING
		public Assignment getReferenceFormulationAssignment_2() { return cReferenceFormulationAssignment_2; }
		
		//STRING
		public RuleCall getReferenceFormulationSTRINGTerminalRuleCall_2_0() { return cReferenceFormulationSTRINGTerminalRuleCall_2_0; }
	}
	public class SourceGroupElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.zazuko.experimental.rmdsl.RdfMapping.SourceGroup");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSourceGroupKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTypeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTypeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cTypeSourceTypeCrossReference_4_0 = (CrossReference)cTypeAssignment_4.eContents().get(0);
		private final RuleCall cTypeSourceTypeIDTerminalRuleCall_4_0_1 = (RuleCall)cTypeSourceTypeCrossReference_4_0.eContents().get(1);
		private final Keyword cSemicolonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cSourceKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cSourceAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cSourceSTRINGTerminalRuleCall_6_1_0 = (RuleCall)cSourceAssignment_6_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_6_2 = (Keyword)cGroup_6.eContents().get(2);
		private final Assignment cLogicalSourcesAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cLogicalSourcesLogicalSourceParserRuleCall_7_0 = (RuleCall)cLogicalSourcesAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//SourceGroup:
		//	'source-group' name=ID '{'
		//	'type' type=[SourceType] ';' ('source' source=STRING ';')?
		//	logicalSources+=LogicalSource*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'source-group' name=ID '{' 'type' type=[SourceType] ';' ('source' source=STRING ';')? logicalSources+=LogicalSource* '}'
		public Group getGroup() { return cGroup; }
		
		//'source-group'
		public Keyword getSourceGroupKeyword_0() { return cSourceGroupKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'type'
		public Keyword getTypeKeyword_3() { return cTypeKeyword_3; }
		
		//type=[SourceType]
		public Assignment getTypeAssignment_4() { return cTypeAssignment_4; }
		
		//[SourceType]
		public CrossReference getTypeSourceTypeCrossReference_4_0() { return cTypeSourceTypeCrossReference_4_0; }
		
		//ID
		public RuleCall getTypeSourceTypeIDTerminalRuleCall_4_0_1() { return cTypeSourceTypeIDTerminalRuleCall_4_0_1; }
		
		//';'
		public Keyword getSemicolonKeyword_5() { return cSemicolonKeyword_5; }
		
		//('source' source=STRING ';')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'source'
		public Keyword getSourceKeyword_6_0() { return cSourceKeyword_6_0; }
		
		//source=STRING
		public Assignment getSourceAssignment_6_1() { return cSourceAssignment_6_1; }
		
		//STRING
		public RuleCall getSourceSTRINGTerminalRuleCall_6_1_0() { return cSourceSTRINGTerminalRuleCall_6_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_6_2() { return cSemicolonKeyword_6_2; }
		
		//logicalSources+=LogicalSource*
		public Assignment getLogicalSourcesAssignment_7() { return cLogicalSourcesAssignment_7; }
		
		//LogicalSource
		public RuleCall getLogicalSourcesLogicalSourceParserRuleCall_7_0() { return cLogicalSourcesLogicalSourceParserRuleCall_7_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class LogicalSourceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.zazuko.experimental.rmdsl.RdfMapping.LogicalSource");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLogicalSourceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTypeKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTypeAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cTypeSourceTypeCrossReference_3_1_0 = (CrossReference)cTypeAssignment_3_1.eContents().get(0);
		private final RuleCall cTypeSourceTypeIDTerminalRuleCall_3_1_0_1 = (RuleCall)cTypeSourceTypeCrossReference_3_1_0.eContents().get(1);
		private final Keyword cSemicolonKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cSourceKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cSourceAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cSourceSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cSourceAssignment_4_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_4_2 = (Keyword)cGroup_4.eContents().get(2);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cIteratorKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cIteratorAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cIteratorSTRINGTerminalRuleCall_5_1_0 = (RuleCall)cIteratorAssignment_5_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_5_2 = (Keyword)cGroup_5.eContents().get(2);
		private final Keyword cReferenceablesKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cLeftCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cReferencablesAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cReferencablesReferenceableParserRuleCall_8_0 = (RuleCall)cReferencablesAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//LogicalSource:
		//	'logical-source' name=ID '{' ('type' type=[SourceType] ';')? ('source' source=STRING ';')? ('iterator' iterator=STRING
		//	';')?
		//	'referenceables' '{'
		//	referencables+=Referenceable*
		//	'}'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'logical-source' name=ID '{' ('type' type=[SourceType] ';')? ('source' source=STRING ';')? ('iterator' iterator=STRING
		//';')? 'referenceables' '{' referencables+=Referenceable* '}' '}'
		public Group getGroup() { return cGroup; }
		
		//'logical-source'
		public Keyword getLogicalSourceKeyword_0() { return cLogicalSourceKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('type' type=[SourceType] ';')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'type'
		public Keyword getTypeKeyword_3_0() { return cTypeKeyword_3_0; }
		
		//type=[SourceType]
		public Assignment getTypeAssignment_3_1() { return cTypeAssignment_3_1; }
		
		//[SourceType]
		public CrossReference getTypeSourceTypeCrossReference_3_1_0() { return cTypeSourceTypeCrossReference_3_1_0; }
		
		//ID
		public RuleCall getTypeSourceTypeIDTerminalRuleCall_3_1_0_1() { return cTypeSourceTypeIDTerminalRuleCall_3_1_0_1; }
		
		//';'
		public Keyword getSemicolonKeyword_3_2() { return cSemicolonKeyword_3_2; }
		
		//('source' source=STRING ';')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'source'
		public Keyword getSourceKeyword_4_0() { return cSourceKeyword_4_0; }
		
		//source=STRING
		public Assignment getSourceAssignment_4_1() { return cSourceAssignment_4_1; }
		
		//STRING
		public RuleCall getSourceSTRINGTerminalRuleCall_4_1_0() { return cSourceSTRINGTerminalRuleCall_4_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_4_2() { return cSemicolonKeyword_4_2; }
		
		//('iterator' iterator=STRING ';')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'iterator'
		public Keyword getIteratorKeyword_5_0() { return cIteratorKeyword_5_0; }
		
		//iterator=STRING
		public Assignment getIteratorAssignment_5_1() { return cIteratorAssignment_5_1; }
		
		//STRING
		public RuleCall getIteratorSTRINGTerminalRuleCall_5_1_0() { return cIteratorSTRINGTerminalRuleCall_5_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_5_2() { return cSemicolonKeyword_5_2; }
		
		//'referenceables'
		public Keyword getReferenceablesKeyword_6() { return cReferenceablesKeyword_6; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7() { return cLeftCurlyBracketKeyword_7; }
		
		//referencables+=Referenceable*
		public Assignment getReferencablesAssignment_8() { return cReferencablesAssignment_8; }
		
		//Referenceable
		public RuleCall getReferencablesReferenceableParserRuleCall_8_0() { return cReferencablesReferenceableParserRuleCall_8_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class ReferenceableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.zazuko.experimental.rmdsl.RdfMapping.Referenceable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_1_0 = (RuleCall)cValueAssignment_1.eContents().get(0);
		
		//Referenceable:
		//	name=ID value=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID value=STRING
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//value=STRING
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_1_0() { return cValueSTRINGTerminalRuleCall_1_0; }
	}
	public class VocabularyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.zazuko.experimental.rmdsl.RdfMapping.Vocabulary");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVocabularyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPrefixAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPrefixPrefixParserRuleCall_3_0 = (RuleCall)cPrefixAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cClassesKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cClassesAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cClassesRdfClassParserRuleCall_4_1_0 = (RuleCall)cClassesAssignment_4_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_4_2 = (Keyword)cGroup_4.eContents().get(2);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPropertiesKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cPropertiesAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cPropertiesRdfPropertyParserRuleCall_5_1_0 = (RuleCall)cPropertiesAssignment_5_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_5_2 = (Keyword)cGroup_5.eContents().get(2);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Vocabulary:
		//	'vocabulary' name=ID '{'
		//	prefix=Prefix ('classes' classes+=RdfClass* ';')? ('properties' properties+=RdfProperty* ';')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'vocabulary' name=ID '{' prefix=Prefix ('classes' classes+=RdfClass* ';')? ('properties' properties+=RdfProperty* ';')?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'vocabulary'
		public Keyword getVocabularyKeyword_0() { return cVocabularyKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//prefix=Prefix
		public Assignment getPrefixAssignment_3() { return cPrefixAssignment_3; }
		
		//Prefix
		public RuleCall getPrefixPrefixParserRuleCall_3_0() { return cPrefixPrefixParserRuleCall_3_0; }
		
		//('classes' classes+=RdfClass* ';')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'classes'
		public Keyword getClassesKeyword_4_0() { return cClassesKeyword_4_0; }
		
		//classes+=RdfClass*
		public Assignment getClassesAssignment_4_1() { return cClassesAssignment_4_1; }
		
		//RdfClass
		public RuleCall getClassesRdfClassParserRuleCall_4_1_0() { return cClassesRdfClassParserRuleCall_4_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_4_2() { return cSemicolonKeyword_4_2; }
		
		//('properties' properties+=RdfProperty* ';')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'properties'
		public Keyword getPropertiesKeyword_5_0() { return cPropertiesKeyword_5_0; }
		
		//properties+=RdfProperty*
		public Assignment getPropertiesAssignment_5_1() { return cPropertiesAssignment_5_1; }
		
		//RdfProperty
		public RuleCall getPropertiesRdfPropertyParserRuleCall_5_1_0() { return cPropertiesRdfPropertyParserRuleCall_5_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_5_2() { return cSemicolonKeyword_5_2; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class PrefixElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.zazuko.experimental.rmdsl.RdfMapping.Prefix");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPrefixKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cLabelAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLabelSTRINGTerminalRuleCall_1_0 = (RuleCall)cLabelAssignment_1.eContents().get(0);
		private final Assignment cIriAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cIriSTRINGTerminalRuleCall_2_0 = (RuleCall)cIriAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Prefix:
		//	'prefix' label=STRING iri=STRING ';';
		@Override public ParserRule getRule() { return rule; }
		
		//'prefix' label=STRING iri=STRING ';'
		public Group getGroup() { return cGroup; }
		
		//'prefix'
		public Keyword getPrefixKeyword_0() { return cPrefixKeyword_0; }
		
		//label=STRING
		public Assignment getLabelAssignment_1() { return cLabelAssignment_1; }
		
		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_1_0() { return cLabelSTRINGTerminalRuleCall_1_0; }
		
		//iri=STRING
		public Assignment getIriAssignment_2() { return cIriAssignment_2; }
		
		//STRING
		public RuleCall getIriSTRINGTerminalRuleCall_2_0() { return cIriSTRINGTerminalRuleCall_2_0; }
		
		//';'
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}
	public class RdfPropertyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.zazuko.experimental.rmdsl.RdfMapping.RdfProperty");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//RdfProperty:
		//	name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	public class RdfClassElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.zazuko.experimental.rmdsl.RdfMapping.RdfClass");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//RdfClass:
		//	name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	public class MappingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.zazuko.experimental.rmdsl.RdfMapping.Mapping");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMapKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cFromKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSourceAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cSourceLogicalSourceCrossReference_3_0 = (CrossReference)cSourceAssignment_3.eContents().get(0);
		private final RuleCall cSourceLogicalSourceQualifiedNameParserRuleCall_3_0_1 = (RuleCall)cSourceLogicalSourceCrossReference_3_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cSubjectKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cTemplateKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cPatternAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cPatternSTRINGTerminalRuleCall_7_0 = (RuleCall)cPatternAssignment_7.eContents().get(0);
		private final Keyword cWithKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cReferenceAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final CrossReference cReferenceReferenceableCrossReference_9_0 = (CrossReference)cReferenceAssignment_9.eContents().get(0);
		private final RuleCall cReferenceReferenceableQualifiedNameParserRuleCall_9_0_1 = (RuleCall)cReferenceReferenceableCrossReference_9_0.eContents().get(1);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cTypesKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cSubjectTypeMappingsAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cSubjectTypeMappingsSubjectTypeMappingParserRuleCall_10_1_0 = (RuleCall)cSubjectTypeMappingsAssignment_10_1.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cPropertiesKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cPoMappingsAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cPoMappingsPredicateObjectMappingParserRuleCall_11_1_0 = (RuleCall)cPoMappingsAssignment_11_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Mapping:
		//	'map' name=ID 'from' source=[LogicalSource|QualifiedName] '{'
		//	'subject' 'template' pattern=STRING 'with' reference=[Referenceable|QualifiedName] ('types'
		//	subjectTypeMappings+=SubjectTypeMapping+)? ('properties' poMappings+=PredicateObjectMapping+)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'map' name=ID 'from' source=[LogicalSource|QualifiedName] '{' 'subject' 'template' pattern=STRING 'with'
		//reference=[Referenceable|QualifiedName] ('types' subjectTypeMappings+=SubjectTypeMapping+)? ('properties'
		//poMappings+=PredicateObjectMapping+)? '}'
		public Group getGroup() { return cGroup; }
		
		//'map'
		public Keyword getMapKeyword_0() { return cMapKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'from'
		public Keyword getFromKeyword_2() { return cFromKeyword_2; }
		
		//source=[LogicalSource|QualifiedName]
		public Assignment getSourceAssignment_3() { return cSourceAssignment_3; }
		
		//[LogicalSource|QualifiedName]
		public CrossReference getSourceLogicalSourceCrossReference_3_0() { return cSourceLogicalSourceCrossReference_3_0; }
		
		//QualifiedName
		public RuleCall getSourceLogicalSourceQualifiedNameParserRuleCall_3_0_1() { return cSourceLogicalSourceQualifiedNameParserRuleCall_3_0_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//'subject'
		public Keyword getSubjectKeyword_5() { return cSubjectKeyword_5; }
		
		//'template'
		public Keyword getTemplateKeyword_6() { return cTemplateKeyword_6; }
		
		//pattern=STRING
		public Assignment getPatternAssignment_7() { return cPatternAssignment_7; }
		
		//STRING
		public RuleCall getPatternSTRINGTerminalRuleCall_7_0() { return cPatternSTRINGTerminalRuleCall_7_0; }
		
		//'with'
		public Keyword getWithKeyword_8() { return cWithKeyword_8; }
		
		//reference=[Referenceable|QualifiedName]
		public Assignment getReferenceAssignment_9() { return cReferenceAssignment_9; }
		
		//[Referenceable|QualifiedName]
		public CrossReference getReferenceReferenceableCrossReference_9_0() { return cReferenceReferenceableCrossReference_9_0; }
		
		//QualifiedName
		public RuleCall getReferenceReferenceableQualifiedNameParserRuleCall_9_0_1() { return cReferenceReferenceableQualifiedNameParserRuleCall_9_0_1; }
		
		//('types' subjectTypeMappings+=SubjectTypeMapping+)?
		public Group getGroup_10() { return cGroup_10; }
		
		//'types'
		public Keyword getTypesKeyword_10_0() { return cTypesKeyword_10_0; }
		
		//subjectTypeMappings+=SubjectTypeMapping+
		public Assignment getSubjectTypeMappingsAssignment_10_1() { return cSubjectTypeMappingsAssignment_10_1; }
		
		//SubjectTypeMapping
		public RuleCall getSubjectTypeMappingsSubjectTypeMappingParserRuleCall_10_1_0() { return cSubjectTypeMappingsSubjectTypeMappingParserRuleCall_10_1_0; }
		
		//('properties' poMappings+=PredicateObjectMapping+)?
		public Group getGroup_11() { return cGroup_11; }
		
		//'properties'
		public Keyword getPropertiesKeyword_11_0() { return cPropertiesKeyword_11_0; }
		
		//poMappings+=PredicateObjectMapping+
		public Assignment getPoMappingsAssignment_11_1() { return cPoMappingsAssignment_11_1; }
		
		//PredicateObjectMapping
		public RuleCall getPoMappingsPredicateObjectMappingParserRuleCall_11_1_0() { return cPoMappingsPredicateObjectMappingParserRuleCall_11_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class SubjectTypeMappingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.zazuko.experimental.rmdsl.RdfMapping.SubjectTypeMapping");
		private final Assignment cTypeAssignment = (Assignment)rule.eContents().get(1);
		private final CrossReference cTypeRdfClassCrossReference_0 = (CrossReference)cTypeAssignment.eContents().get(0);
		private final RuleCall cTypeRdfClassQualifiedNameParserRuleCall_0_1 = (RuleCall)cTypeRdfClassCrossReference_0.eContents().get(1);
		
		//SubjectTypeMapping:
		//	type=[RdfClass|QualifiedName];
		@Override public ParserRule getRule() { return rule; }
		
		//type=[RdfClass|QualifiedName]
		public Assignment getTypeAssignment() { return cTypeAssignment; }
		
		//[RdfClass|QualifiedName]
		public CrossReference getTypeRdfClassCrossReference_0() { return cTypeRdfClassCrossReference_0; }
		
		//QualifiedName
		public RuleCall getTypeRdfClassQualifiedNameParserRuleCall_0_1() { return cTypeRdfClassQualifiedNameParserRuleCall_0_1; }
	}
	public class PredicateObjectMappingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.zazuko.experimental.rmdsl.RdfMapping.PredicateObjectMapping");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPropertyAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cPropertyRdfPropertyCrossReference_0_0 = (CrossReference)cPropertyAssignment_0.eContents().get(0);
		private final RuleCall cPropertyRdfPropertyQualifiedNameParserRuleCall_0_0_1 = (RuleCall)cPropertyRdfPropertyCrossReference_0_0.eContents().get(1);
		private final Keyword cFromKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cReferenceAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cReferenceReferenceableCrossReference_2_0 = (CrossReference)cReferenceAssignment_2.eContents().get(0);
		private final RuleCall cReferenceReferenceableQualifiedNameParserRuleCall_2_0_1 = (RuleCall)cReferenceReferenceableCrossReference_2_0.eContents().get(1);
		
		//PredicateObjectMapping:
		//	property=[RdfProperty|QualifiedName] 'from' reference=[Referenceable|QualifiedName];
		@Override public ParserRule getRule() { return rule; }
		
		//property=[RdfProperty|QualifiedName] 'from' reference=[Referenceable|QualifiedName]
		public Group getGroup() { return cGroup; }
		
		//property=[RdfProperty|QualifiedName]
		public Assignment getPropertyAssignment_0() { return cPropertyAssignment_0; }
		
		//[RdfProperty|QualifiedName]
		public CrossReference getPropertyRdfPropertyCrossReference_0_0() { return cPropertyRdfPropertyCrossReference_0_0; }
		
		//QualifiedName
		public RuleCall getPropertyRdfPropertyQualifiedNameParserRuleCall_0_0_1() { return cPropertyRdfPropertyQualifiedNameParserRuleCall_0_0_1; }
		
		//'from'
		public Keyword getFromKeyword_1() { return cFromKeyword_1; }
		
		//reference=[Referenceable|QualifiedName]
		public Assignment getReferenceAssignment_2() { return cReferenceAssignment_2; }
		
		//[Referenceable|QualifiedName]
		public CrossReference getReferenceReferenceableCrossReference_2_0() { return cReferenceReferenceableCrossReference_2_0; }
		
		//QualifiedName
		public RuleCall getReferenceReferenceableQualifiedNameParserRuleCall_2_0_1() { return cReferenceReferenceableQualifiedNameParserRuleCall_2_0_1; }
	}
	public class ImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.zazuko.experimental.rmdsl.RdfMapping.Import");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cImportKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cImportedNamespaceAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_0 = (RuleCall)cImportedNamespaceAssignment_1.eContents().get(0);
		
		//Import:
		//	'import' importedNamespace=QualifiedNameWithWildcard;
		@Override public ParserRule getRule() { return rule; }
		
		//'import' importedNamespace=QualifiedNameWithWildcard
		public Group getGroup() { return cGroup; }
		
		//'import'
		public Keyword getImportKeyword_0() { return cImportKeyword_0; }
		
		//importedNamespace=QualifiedNameWithWildcard
		public Assignment getImportedNamespaceAssignment_1() { return cImportedNamespaceAssignment_1; }
		
		//QualifiedNameWithWildcard
		public RuleCall getImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_0() { return cImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_0; }
	}
	public class QualifiedNameWithWildcardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.zazuko.experimental.rmdsl.RdfMapping.QualifiedNameWithWildcard");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cQualifiedNameParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopAsteriskKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//QualifiedNameWithWildcard:
		//	QualifiedName '.*'?;
		@Override public ParserRule getRule() { return rule; }
		
		//QualifiedName '.*'?
		public Group getGroup() { return cGroup; }
		
		//QualifiedName
		public RuleCall getQualifiedNameParserRuleCall_0() { return cQualifiedNameParserRuleCall_0; }
		
		//'.*'?
		public Keyword getFullStopAsteriskKeyword_1() { return cFullStopAsteriskKeyword_1; }
	}
	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.zazuko.experimental.rmdsl.RdfMapping.QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//	ID ('.' ID)*;
		@Override public ParserRule getRule() { return rule; }
		
		//ID ('.' ID)*
		public Group getGroup() { return cGroup; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//('.' ID)*
		public Group getGroup_1() { return cGroup_1; }
		
		//'.'
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	
	
	private final DomainmodelElements pDomainmodel;
	private final ElementElements pElement;
	private final SourceTypesDefinitionElements pSourceTypesDefinition;
	private final SourceTypeElements pSourceType;
	private final SourceGroupElements pSourceGroup;
	private final LogicalSourceElements pLogicalSource;
	private final ReferenceableElements pReferenceable;
	private final VocabularyElements pVocabulary;
	private final PrefixElements pPrefix;
	private final RdfPropertyElements pRdfProperty;
	private final RdfClassElements pRdfClass;
	private final MappingElements pMapping;
	private final SubjectTypeMappingElements pSubjectTypeMapping;
	private final PredicateObjectMappingElements pPredicateObjectMapping;
	private final ImportElements pImport;
	private final QualifiedNameWithWildcardElements pQualifiedNameWithWildcard;
	private final QualifiedNameElements pQualifiedName;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public RdfMappingGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pDomainmodel = new DomainmodelElements();
		this.pElement = new ElementElements();
		this.pSourceTypesDefinition = new SourceTypesDefinitionElements();
		this.pSourceType = new SourceTypeElements();
		this.pSourceGroup = new SourceGroupElements();
		this.pLogicalSource = new LogicalSourceElements();
		this.pReferenceable = new ReferenceableElements();
		this.pVocabulary = new VocabularyElements();
		this.pPrefix = new PrefixElements();
		this.pRdfProperty = new RdfPropertyElements();
		this.pRdfClass = new RdfClassElements();
		this.pMapping = new MappingElements();
		this.pSubjectTypeMapping = new SubjectTypeMappingElements();
		this.pPredicateObjectMapping = new PredicateObjectMappingElements();
		this.pImport = new ImportElements();
		this.pQualifiedNameWithWildcard = new QualifiedNameWithWildcardElements();
		this.pQualifiedName = new QualifiedNameElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("com.zazuko.experimental.rmdsl.RdfMapping".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Domainmodel:
	//	elements+=Element*;
	public DomainmodelElements getDomainmodelAccess() {
		return pDomainmodel;
	}
	
	public ParserRule getDomainmodelRule() {
		return getDomainmodelAccess().getRule();
	}
	
	//Element:
	//	Import | SourceTypesDefinition | SourceGroup | LogicalSource | Vocabulary | Mapping;
	public ElementElements getElementAccess() {
		return pElement;
	}
	
	public ParserRule getElementRule() {
		return getElementAccess().getRule();
	}
	
	//SourceTypesDefinition:
	//	{SourceTypesDefinition}
	//	'source-types' '{'
	//	types+=SourceType*
	//	'}';
	public SourceTypesDefinitionElements getSourceTypesDefinitionAccess() {
		return pSourceTypesDefinition;
	}
	
	public ParserRule getSourceTypesDefinitionRule() {
		return getSourceTypesDefinitionAccess().getRule();
	}
	
	//SourceType:
	//	name=ID 'referenceFormulation' referenceFormulation=STRING;
	public SourceTypeElements getSourceTypeAccess() {
		return pSourceType;
	}
	
	public ParserRule getSourceTypeRule() {
		return getSourceTypeAccess().getRule();
	}
	
	//SourceGroup:
	//	'source-group' name=ID '{'
	//	'type' type=[SourceType] ';' ('source' source=STRING ';')?
	//	logicalSources+=LogicalSource*
	//	'}';
	public SourceGroupElements getSourceGroupAccess() {
		return pSourceGroup;
	}
	
	public ParserRule getSourceGroupRule() {
		return getSourceGroupAccess().getRule();
	}
	
	//LogicalSource:
	//	'logical-source' name=ID '{' ('type' type=[SourceType] ';')? ('source' source=STRING ';')? ('iterator' iterator=STRING
	//	';')?
	//	'referenceables' '{'
	//	referencables+=Referenceable*
	//	'}'
	//	'}';
	public LogicalSourceElements getLogicalSourceAccess() {
		return pLogicalSource;
	}
	
	public ParserRule getLogicalSourceRule() {
		return getLogicalSourceAccess().getRule();
	}
	
	//Referenceable:
	//	name=ID value=STRING;
	public ReferenceableElements getReferenceableAccess() {
		return pReferenceable;
	}
	
	public ParserRule getReferenceableRule() {
		return getReferenceableAccess().getRule();
	}
	
	//Vocabulary:
	//	'vocabulary' name=ID '{'
	//	prefix=Prefix ('classes' classes+=RdfClass* ';')? ('properties' properties+=RdfProperty* ';')?
	//	'}';
	public VocabularyElements getVocabularyAccess() {
		return pVocabulary;
	}
	
	public ParserRule getVocabularyRule() {
		return getVocabularyAccess().getRule();
	}
	
	//Prefix:
	//	'prefix' label=STRING iri=STRING ';';
	public PrefixElements getPrefixAccess() {
		return pPrefix;
	}
	
	public ParserRule getPrefixRule() {
		return getPrefixAccess().getRule();
	}
	
	//RdfProperty:
	//	name=ID;
	public RdfPropertyElements getRdfPropertyAccess() {
		return pRdfProperty;
	}
	
	public ParserRule getRdfPropertyRule() {
		return getRdfPropertyAccess().getRule();
	}
	
	//RdfClass:
	//	name=ID;
	public RdfClassElements getRdfClassAccess() {
		return pRdfClass;
	}
	
	public ParserRule getRdfClassRule() {
		return getRdfClassAccess().getRule();
	}
	
	//Mapping:
	//	'map' name=ID 'from' source=[LogicalSource|QualifiedName] '{'
	//	'subject' 'template' pattern=STRING 'with' reference=[Referenceable|QualifiedName] ('types'
	//	subjectTypeMappings+=SubjectTypeMapping+)? ('properties' poMappings+=PredicateObjectMapping+)?
	//	'}';
	public MappingElements getMappingAccess() {
		return pMapping;
	}
	
	public ParserRule getMappingRule() {
		return getMappingAccess().getRule();
	}
	
	//SubjectTypeMapping:
	//	type=[RdfClass|QualifiedName];
	public SubjectTypeMappingElements getSubjectTypeMappingAccess() {
		return pSubjectTypeMapping;
	}
	
	public ParserRule getSubjectTypeMappingRule() {
		return getSubjectTypeMappingAccess().getRule();
	}
	
	//PredicateObjectMapping:
	//	property=[RdfProperty|QualifiedName] 'from' reference=[Referenceable|QualifiedName];
	public PredicateObjectMappingElements getPredicateObjectMappingAccess() {
		return pPredicateObjectMapping;
	}
	
	public ParserRule getPredicateObjectMappingRule() {
		return getPredicateObjectMappingAccess().getRule();
	}
	
	//Import:
	//	'import' importedNamespace=QualifiedNameWithWildcard;
	public ImportElements getImportAccess() {
		return pImport;
	}
	
	public ParserRule getImportRule() {
		return getImportAccess().getRule();
	}
	
	//QualifiedNameWithWildcard:
	//	QualifiedName '.*'?;
	public QualifiedNameWithWildcardElements getQualifiedNameWithWildcardAccess() {
		return pQualifiedNameWithWildcard;
	}
	
	public ParserRule getQualifiedNameWithWildcardRule() {
		return getQualifiedNameWithWildcardAccess().getRule();
	}
	
	//QualifiedName:
	//	ID ('.' ID)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return pQualifiedName;
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
