/*
 * generated by Xtext 2.14.0
 */
package com.zazuko.experimental.rmdsl.ui.tests;

import com.google.inject.Injector;
import com.zazuko.experimental.rmdsl.ui.internal.RmdslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class RdfMappingUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RmdslActivator.getInstance().getInjector("com.zazuko.experimental.rmdsl.RdfMapping");
	}

}
