/**
 * generated by Xtext 2.14.0
 */
package com.zazuko.experimental.rmdsl;

import com.zazuko.experimental.rmdsl.RdfMappingStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RdfMappingStandaloneSetup extends RdfMappingStandaloneSetupGenerated {
  public static void doSetup() {
    new RdfMappingStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
